app = "your-bot-name"
primary_region = "sin"  # Singapore, adjust to your region

[build]
  dockerfile = "Dockerfile"

[mounts]
  source = "bot_data"
  destination = "/data"

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1